# Generated by Django 5.1.1 on 2024-10-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imovel_tipo", models.CharField(max_length=65)),
                ("imovel_codigo", models.IntegerField(max_length=65)),
                ("imovel_m2", models.IntegerField(max_length=65)),
                ("imovel_endereco", models.IntegerField(max_length=255)),
                ("imovel_valor", models.IntegerField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
