# Generated by Django 5.1.1 on 2024-10-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcrawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imovel",
            name="imovel_codigo",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_endereco",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_m2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_valor",
            field=models.IntegerField(),
        ),
    ]
