# Generated by Django 5.1.1 on 2024-10-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcrawler", "0002_alter_imovel_imovel_codigo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imovel",
            name="imovel_codigo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_endereco",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_m2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_tipo",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_valor",
            field=models.CharField(max_length=100),
        ),
    ]
