# Generated by Django 5.1.3 on 2024-11-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcrawler", "0006_alter_imovel_imovel_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="imovel_bairro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="imovel",
            name="imovel_cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="imovel",
            name="imovel_rua",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="imovel",
            name="imovel_site",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
