# Generated by Django 5.1.3 on 2024-11-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcrawler", "0007_imovel_imovel_bairro_imovel_imovel_cidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imovel_Caio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imovel_titulo", models.CharField(max_length=500)),
                ("imovel_tipo", models.CharField(max_length=100)),
                ("imovel_valor", models.FloatField()),
                ("imovel_caracteristicas", models.CharField(max_length=500)),
                ("imovel_codigo", models.IntegerField(blank=True, null=True)),
                (
                    "imovel_site",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_tipo",
            field=models.CharField(max_length=100),
        ),
    ]
