# Generated by Django 5.1.3 on 2024-11-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcrawler", "0008_imovel_caio_alter_imovel_imovel_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imovel",
            name="imovel_bairro",
        ),
        migrations.RemoveField(
            model_name="imovel",
            name="imovel_cidade",
        ),
        migrations.RemoveField(
            model_name="imovel",
            name="imovel_m2",
        ),
        migrations.RemoveField(
            model_name="imovel",
            name="imovel_rua",
        ),
        migrations.AddField(
            model_name="imovel",
            name="imovel_caracteristicas",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="imovel",
            name="imovel_titulo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="imovel_tipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
