# Generated by Django 5.1.3 on 2024-11-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcrawler", "0009_remove_imovel_imovel_bairro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imovel_MG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imovel_titulo", models.CharField(max_length=500)),
                ("imovel_tipo", models.CharField(max_length=100)),
                ("imovel_codigo", models.IntegerField(blank=True, null=True)),
                ("imovel_valor", models.FloatField()),
                ("imovel_caracteristicas", models.CharField(max_length=500)),
                ("imovel_endereco", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
