# Generated by Django 5.1.3 on 2024-11-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcrawler", "0010_imovel_mg"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel_mg",
            name="imovel_site",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
